"""Add Veille models

Revision ID: 47b94d666c67
Revises: 
Create Date: 2026-06-30 14:32:17.474507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b94d666c67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('veille_alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veille_alert_rules_id'), 'veille_alert_rules', ['id'], unique=False)
    op.create_index(op.f('ix_veille_alert_rules_user_id'), 'veille_alert_rules', ['user_id'], unique=False)
    op.create_table('veille_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_scraped', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veille_sources_id'), 'veille_sources', ['id'], unique=False)
    op.create_index(op.f('ix_veille_sources_name'), 'veille_sources', ['name'], unique=False)
    op.create_table('veille_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['veille_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veille_articles_doi'), 'veille_articles', ['doi'], unique=True)
    op.create_index(op.f('ix_veille_articles_id'), 'veille_articles', ['id'], unique=False)
    op.create_index(op.f('ix_veille_articles_title'), 'veille_articles', ['title'], unique=False)
    op.create_table('veille_alert_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['veille_articles.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['veille_alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veille_alert_notifications_id'), 'veille_alert_notifications', ['id'], unique=False)
    op.create_table('veille_article_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['veille_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veille_article_summaries_id'), 'veille_article_summaries', ['id'], unique=False)
    op.create_table('veille_article_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.Column('tag', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['veille_articles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_veille_article_tags_id'), 'veille_article_tags', ['id'], unique=False)
    op.create_index(op.f('ix_veille_article_tags_tag'), 'veille_article_tags', ['tag'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_veille_article_tags_tag'), table_name='veille_article_tags')
    op.drop_index(op.f('ix_veille_article_tags_id'), table_name='veille_article_tags')
    op.drop_table('veille_article_tags')
    op.drop_index(op.f('ix_veille_article_summaries_id'), table_name='veille_article_summaries')
    op.drop_table('veille_article_summaries')
    op.drop_index(op.f('ix_veille_alert_notifications_id'), table_name='veille_alert_notifications')
    op.drop_table('veille_alert_notifications')
    op.drop_index(op.f('ix_veille_articles_title'), table_name='veille_articles')
    op.drop_index(op.f('ix_veille_articles_id'), table_name='veille_articles')
    op.drop_index(op.f('ix_veille_articles_doi'), table_name='veille_articles')
    op.drop_table('veille_articles')
    op.drop_index(op.f('ix_veille_sources_name'), table_name='veille_sources')
    op.drop_index(op.f('ix_veille_sources_id'), table_name='veille_sources')
    op.drop_table('veille_sources')
    op.drop_index(op.f('ix_veille_alert_rules_user_id'), table_name='veille_alert_rules')
    op.drop_index(op.f('ix_veille_alert_rules_id'), table_name='veille_alert_rules')
    op.drop_table('veille_alert_rules')
    # ### end Alembic commands ###
